### PR TITLE
Issue 2917

### PR DESCRIPTION
**Pull request by tilmanschweitzer**
I tried to fix the failing tests in your PR https://github.com/angular/protractor/pull/3972

Actually, I'm not sure if my changes to element.ts are correct, because this part of the code is quite complex. Although they prevent exceptions in the expected conditions, they return undefined for all test cases I added.

I also added some test cases to cover the other expected condition methods.

### CODE REVIEW

**Comment by tilmanschweitzer** [comment]
@sjelin Should I open the PR directly to the protractor repo?

If you merge my changes to your branch first, the discussion in https://github.com/angular/protractor/pull/3972 is not lost.

**Comment by tilmanschweitzer** [comment]
The changes until e27c035  worked on CircleCI

https://circleci.com/gh/tilmanpotthof/protractor/7

**Comment by tilmanschweitzer** [comment]
a7f700f is failing as described

https://circleci.com/gh/tilmanpotthof/protractor/9

**Comment by sjelin** [comment]
Hey, thanks for the fix + testcases!  Probably the best thing to do is for you to submit this as a PR against protractor directly, then I'll clean it up a bit (just to make it more consistant with other protractor changes) and merge it in

**Pull request closed without merging**
